---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: luksa-kubia
        image: luksa/kubia
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "80m"
          limits:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: kubia-service
spec:
  # type: ClusterIP
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: kubia
